"""add category_id to service

Revision ID: 06dad708d201
Revises: e80b1fa99a38
Create Date: 2026-02-23 10:56:49.502902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06dad708d201'
down_revision = 'e80b1fa99a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_old', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('custom_data', sa.JSON(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_service_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_seller_id'), ['seller_id'], unique=False)
        batch_op.create_foreign_key(
    'fk_service_category_id',   # required name
    'category',
    ['category_id'],
    ['id']
)
        batch_op.drop_column('category')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_online')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_service_seller_id'))
        batch_op.drop_index(batch_op.f('ix_service_category_id'))
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('custom_data')
        batch_op.drop_column('category_old')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
