"""Add online status to User

Revision ID: 38c485b37f19
Revises: d699bc3b005b
Create Date: 2026-01-31 11:46:26.183945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c485b37f19'
down_revision = 'd699bc3b005b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('is_online')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('delivered')

    # ### end Alembic commands ###
