"""Add read_at column to message

Revision ID: 5654bcf86dd7
Revises: 38c485b37f19
Create Date: 2026-02-06 18:40:38.121277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5654bcf86dd7'
down_revision = '38c485b37f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('delivered')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_online')
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_online', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('read_at')

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
