"""add question table

Revision ID: 7ff961844ae8
Revises: b785c2f60f31
Create Date: 2026-02-26 05:12:43.789200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff961844ae8'
down_revision = 'b785c2f60f31'
branch_labels = None
depends_on = None


def upgrade():
    pass  # skipped

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
