"""add can_sell column to user

Revision ID: 9910f7de7e4b
Revises: ce54f7fef292
Create Date: 2026-03-10 15:24:27.311464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9910f7de7e4b'
down_revision = 'ce54f7fef292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('deliverables')
        batch_op.drop_column('description')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('title')
        batch_op.drop_column('deadline')
        batch_op.drop_column('buyer_instructions')
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('paid_at')
        batch_op.drop_column('package_id')

    with op.batch_alter_table('service_image', schema=None) as batch_op:
        batch_op.alter_column('service_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('service_video', schema=None) as batch_op:
        batch_op.alter_column('service_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_sell', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_sell')

    with op.batch_alter_table('service_video', schema=None) as batch_op:
        batch_op.alter_column('service_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('service_image', schema=None) as batch_op:
        batch_op.alter_column('service_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('paid_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('buyer_instructions', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('deadline', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
        batch_op.add_column(sa.Column('started_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('deliverables', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))

    # ### end Alembic commands ###
