"""Initial MySQL migration

Revision ID: ce54f7fef292
Revises: 7ff961844ae8
Create Date: 2026-03-06 13:57:10.873997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce54f7fef292'
down_revision = '7ff961844ae8'
branch_labels = None
depends_on = None


def upgrade():
    pass  # skipped

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payout')
    op.drop_table('payment')
    op.drop_table('message_notification')
    with op.batch_alter_table('service_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_view_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_service_view_service_id'))

    op.drop_table('service_view')
    op.drop_table('service_video')
    op.drop_table('service_package')
    op.drop_table('service_image')
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_service_id'))
        batch_op.drop_index(batch_op.f('ix_review_seller_id'))
        batch_op.drop_index(batch_op.f('ix_review_created_at'))
        batch_op.drop_index(batch_op.f('ix_review_buyer_id'))

    op.drop_table('review')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_service_id'))
        batch_op.drop_index(batch_op.f('ix_question_created_at'))
        batch_op.drop_index(batch_op.f('ix_question_asker_id'))

    op.drop_table('question')
    op.drop_table('order')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    op.drop_table('message')
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_user_id'))

    op.drop_table('favorite')
    op.drop_table('custom_offer')
    op.drop_table('call')
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_seller_id'))
        batch_op.drop_index(batch_op.f('ix_service_category_id'))

    op.drop_table('service')
    op.drop_table('seller_level')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_user_id'))
        batch_op.drop_index(batch_op.f('ix_location_timestamp'))
        batch_op.drop_index(batch_op.f('ix_location_is_active'))

    op.drop_table('location')
    op.drop_table('id_verification_audit')
    op.drop_table('conversation')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
