"""initial migration

Revision ID: d699bc3b005b
Revises: 
Create Date: 2025-12-02 16:43:13.307791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd699bc3b005b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass  # skipped

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payout')
    op.drop_table('payment')
    op.drop_table('service_video')
    op.drop_table('service_image')
    op.drop_table('order')
    op.drop_table('message')
    op.drop_table('service')
    op.drop_table('id_verification_audit')
    op.drop_table('conversation')
    op.drop_table('user')
    # ### end Alembic commands ###
