"""initial migration

Revision ID: d699bc3b005b
Revises: 
Create Date: 2025-12-02 16:43:13.307791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd699bc3b005b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('id_document', sa.String(length=256), nullable=True),
    sa.Column('id_image', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('id_verification_score', sa.Float(), nullable=True),
    sa.Column('id_verified', sa.Boolean(), nullable=True),
    sa.Column('vision_message', sa.String(length=500), nullable=True),
    sa.Column('resubmission_notes', sa.Text(), nullable=True),
    sa.Column('id_front_document', sa.String(length=255), nullable=True),
    sa.Column('id_back_document', sa.String(length=255), nullable=True),
    sa.Column('id_document_path', sa.String(length=500), nullable=True),
    sa.Column('id_confidence_score', sa.Float(), nullable=True),
    sa.Column('id_content_score', sa.Float(), nullable=True),
    sa.Column('id_integrity_score', sa.Float(), nullable=True),
    sa.Column('id_quality_score', sa.Float(), nullable=True),
    sa.Column('id_face_score', sa.Float(), nullable=True),
    sa.Column('id_validation_reasons', sa.Text(), nullable=True),
    sa.Column('id_integrity_issues', sa.Text(), nullable=True),
    sa.Column('id_fields_extracted', sa.Text(), nullable=True),
    sa.Column('manual_review_required', sa.Boolean(), nullable=True),
    sa.Column('manual_review_status', sa.String(length=20), nullable=True),
    sa.Column('manual_review_notes', sa.Text(), nullable=True),
    sa.Column('manual_reviewed_by', sa.Integer(), nullable=True),
    sa.Column('manual_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('id_retry_count', sa.Integer(), nullable=True),
    sa.Column('last_id_upload_at', sa.DateTime(), nullable=True),
    sa.Column('id_submission_ip', sa.String(length=45), nullable=True),
    sa.Column('auto_rejection_reasons', sa.Text(), nullable=True),
    sa.Column('mpesa_phone', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['manual_reviewed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('id_verification_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verification_type', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('content_score', sa.Float(), nullable=True),
    sa.Column('integrity_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('face_score', sa.Float(), nullable=True),
    sa.Column('extracted_fields', sa.Text(), nullable=True),
    sa.Column('validation_reasons', sa.Text(), nullable=True),
    sa.Column('integrity_issues', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('decision_reason', sa.String(length=200), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('quality', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('image_filenames', sa.Text(), nullable=True),
    sa.Column('video_filenames', sa.Text(), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=50), nullable=True),
    sa.Column('merchant_request_id', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payout_status', sa.String(length=20), nullable=True),
    sa.Column('payout_transaction_id', sa.String(length=50), nullable=True),
    sa.Column('payout_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], name='fk_payment_buyer_id'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='fk_payment_order_id'),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], name='fk_payment_seller_id'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name='fk_payment_service_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('originator_conversation_id', sa.String(length=50), nullable=True),
    sa.Column('conversation_id', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('initiator_response', sa.Text(), nullable=True),
    sa.Column('result_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='fk_payout_order_id'),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], name='fk_payout_seller_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payout')
    op.drop_table('payment')
    op.drop_table('service_video')
    op.drop_table('service_image')
    op.drop_table('order')
    op.drop_table('message')
    op.drop_table('service')
    op.drop_table('id_verification_audit')
    op.drop_table('conversation')
    op.drop_table('user')
    # ### end Alembic commands ###
