"""Add location_id to Message model

Revision ID: e80b1fa99a38
Revises: 2cb79d9075f7
Create Date: 2026-02-11 05:18:15.043851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80b1fa99a38'
down_revision = '2cb79d9075f7'
branch_labels = None
depends_on = None


def upgrade():
    pass  # skipped

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_message_location_id', type_='foreignkey')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
