"""add is_active and is_sold to service

Revision ID: fbf91679f948
Revises: 9ce45a293354
Create Date: 2026-03-16 01:04:16.991622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbf91679f948'
down_revision = '9ce45a293354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_package', schema=None) as batch_op:
        batch_op.alter_column('buyer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_package', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               nullable=True)
        batch_op.alter_column('buyer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
